@tool
extends "res://addons/godot_mcp/commands/base_command.gd"

## Tween surface - create reusable tween helper scripts + document runtime Tween API.


func get_commands() -> Dictionary:
	return {
		"create_tween_helper_script": _create_tween_helper_script,
		"list_tween_recipes": _list_tween_recipes,
		"create_scene_tree_tween_snippet": _create_scene_tree_tween_snippet,
	}


func _list_tween_recipes(_params: Dictionary) -> Dictionary:
	return success({
		"recipes": [
			{"id": "fade_in", "props": ["modulate:a 0->1"], "method": "tween_property"},
			{"id": "fade_out", "props": ["modulate:a 1->0"]},
			{"id": "move_to", "props": ["position -> target"]},
			{"id": "scale_pop", "props": ["scale 0->1 with TRANS_BACK"]},
			{"id": "punch_scale", "props": ["scale overshoot then settle"]},
			{"id": "color_flash", "props": ["modulate flash then restore"]},
			{"id": "follow_path", "props": ["PathFollow progress 0->1"]},
		],
		"runtime_api": "node.create_tween() / get_tree().create_tween() - Tween is not a saved Resource; use helper script or snippets.",
		"hint": "create_tween_helper_script writes a reusable Autoload-friendly helper; create_scene_tree_tween_snippet pastes into a .gd file.",
	})


func _create_tween_helper_script(params: Dictionary) -> Dictionary:
	var path: String = optional_string(params, "path", "res://scripts/tween_helper.gd")
	if not path.begins_with("res://"):
		path = "res://" + path.trim_prefix("/")
	if FileAccess.file_exists(path) and not optional_bool(params, "overwrite", false):
		return error(-32000, "Exists: %s" % path, {"suggestion": "overwrite=true"})
	var content := """extends Node
## Generated by Godot MCP - project-neutral Tween helpers.
## Attach as Autoload or instance; call from any node.

func fade(node: CanvasItem, to_alpha: float, duration: float = 0.3, from_alpha: float = -1.0) -> Tween:
	var tw := node.create_tween()
	if from_alpha >= 0.0:
		var c := node.modulate
		c.a = from_alpha
		node.modulate = c
	tw.tween_property(node, "modulate:a", to_alpha, duration)
	return tw

func move_to(node: Node, property: String, target: Variant, duration: float = 0.4, trans := Tween.TRANS_QUAD, ease := Tween.EASE_OUT) -> Tween:
	var tw := node.create_tween()
	tw.set_trans(trans).set_ease(ease)
	tw.tween_property(node, property, target, duration)
	return tw

func scale_to(node: Node, target: Vector2, duration: float = 0.25, trans := Tween.TRANS_BACK, ease := Tween.EASE_OUT) -> Tween:
	var tw := node.create_tween()
	tw.set_trans(trans).set_ease(ease)
	tw.tween_property(node, "scale", target, duration)
	return tw

func punch_scale(node: Node, peak: Vector2 = Vector2(1.15, 1.15), up: float = 0.08, down: float = 0.12) -> Tween:
	var base: Vector2 = node.scale
	var tw := node.create_tween()
	tw.tween_property(node, "scale", peak, up).set_trans(Tween.TRANS_QUAD).set_ease(Tween.EASE_OUT)
	tw.tween_property(node, "scale", base, down).set_trans(Tween.TRANS_BOUNCE).set_ease(Tween.EASE_OUT)
	return tw

func parallel_fade_move(node: Node2D, target_pos: Vector2, to_alpha: float = 1.0, duration: float = 0.35) -> Tween:
	var tw := node.create_tween().set_parallel(true)
	tw.tween_property(node, "position", target_pos, duration)
	tw.tween_property(node, "modulate:a", to_alpha, duration)
	return tw
"""
	var derr := ensure_parent_dir(path)
	if not derr.is_empty():
		return derr
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		return error_internal("Cannot write %s" % path)
	f.store_string(content)
	f.close()
	EditorInterface.get_resource_filesystem().update_file(path)
	return success({
		"path": path,
		"created": true,
		"hint": "Optional: add_autoload path=%s name=TweenHelper" % path,
	})


func _create_scene_tree_tween_snippet(params: Dictionary) -> Dictionary:
	## Insert a tween recipe into an existing GDScript (or return snippet only).
	var recipe: String = optional_string(params, "recipe", "fade_in")
	var node_expr: String = optional_string(params, "node_expr", "self")
	var duration: float = float(params.get("duration", 0.3))
	var snippet := ""
	match recipe:
		"fade_in":
			snippet = "var _tw := %s.create_tween()\n_tw.tween_property(%s, \"modulate:a\", 1.0, %s)\n" % [node_expr, node_expr, str(duration)]
		"fade_out":
			snippet = "var _tw := %s.create_tween()\n_tw.tween_property(%s, \"modulate:a\", 0.0, %s)\n" % [node_expr, node_expr, str(duration)]
		"move_to":
			var target: String = optional_string(params, "target", "Vector2(0, 0)")
			snippet = "var _tw := %s.create_tween()\n_tw.tween_property(%s, \"position\", %s, %s)\n" % [node_expr, node_expr, target, str(duration)]
		"scale_pop":
			snippet = "var _tw := %s.create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)\n_tw.tween_property(%s, \"scale\", Vector2.ONE, %s)\n" % [node_expr, node_expr, str(duration)]
		_:
			snippet = "var _tw := %s.create_tween()\n# customize: _tw.tween_property(...)\n" % node_expr
	var path: String = optional_string(params, "path", "")
	if path.is_empty():
		return success({"recipe": recipe, "snippet": snippet, "written": false})
	if not path.begins_with("res://"):
		path = "res://" + path.trim_prefix("/")
	if not FileAccess.file_exists(path):
		return error_not_found(path)
	var f := FileAccess.open(path, FileAccess.READ)
	var text := f.get_as_text()
	f.close()
	var marker: String = optional_string(params, "after", "")
	if not marker.is_empty() and text.contains(marker):
		text = text.replace(marker, marker + "\n" + snippet)
	else:
		text = text.rstrip() + "\n\n" + snippet
	var wf := FileAccess.open(path, FileAccess.WRITE)
	wf.store_string(text)
	wf.close()
	EditorInterface.get_resource_filesystem().update_file(path)
	return success({"recipe": recipe, "snippet": snippet, "path": path, "written": true})
